Capstone/FarmStore3/Models/AddProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FarmStore3.Models
{
    public class AddProductViewModel
    {
        public string ProduceName { get; set; }
        public int ProduceID { get; set; }
        public int StockQuantity { get; set; }
        public int UnitPrice { get; set; }
        public bool InSeason { get; set; }
    }
}

Capstone/FarmStore3/Models/ErrorViewModel.cs
using System;

namespace FarmStore3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public string ErrorMessage { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Capstone/FarmStore3/Models/ProductListItemViewModel.cs
using FarmStore3.DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FarmStore3.Models
{
    public class ProductListItemViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public ProductListItemViewModel(FarmDALModel dalModel)
        {
            ID = dalModel.ProduceID;
            Name = dalModel.ProduceName;
        }
    }
}

Capstone/FarmStore3/Models/ProductViewModel.cs
using System.Collections.Generic;

namespace FarmStore3.Models
{
    public class ProductViewModel
    {
        public IEnumerable<Products> Products { get; set; }
        public IEnumerable<ProductListItemViewModel> ListOfProducts { get; set; }

    }
}

Capstone/FarmStore3/Models/Products.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FarmStore3.Models
{
    public class Products
    {
        public int ProduceID { get; set; }
        public string ProduceName { get; set; }
        public int CartQuantity { get; set; }
        public int StockQuantity { get; set; }
        public decimal UnitPrice { get; set; }
        public bool InSeason { get; set; }

    }
}

Capstone/FarmStore3/Controllers/FarmController.cs
using FarmStore3.FarmServices;
using FarmStore3.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FarmStore3.Controllers
{
    public class FarmController : Controller
    {
        private readonly IFarmService _farmService;
        public FarmController(IFarmService productService)
        {
            _farmService = productService;
        }
        public IActionResult GetAllProduce()
        {
            var result = _farmService.GetAllProducts();
            return View(result);
        }

        public IActionResult Produce()
        {
            return View();
        }

        public IActionResult AddProduce(AddProductViewModel model)
        {
            var productsViewModel = _farmService.AddNewProduct(model);
            if (!ModelState.IsValid)
            {
                return View("Error", new ErrorViewModel
                { ErrorMessage = "Error product was not added correctly" });
            }
            else
            {
                return View("Produce", productsViewModel);
            }
        }


        public IActionResult FarmStore()
        {
            return View();
        }

        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult DeletProduce()
        {
            return View();
        }

        public IActionResult UpdateProduce(int id, Products produce)
        {
            var updatedProduce = _farmService.UpdateProduce(id, produce);
            var view = _farmService.GetProducts();
            return View("Produce", view);
        }

        public IActionResult Home()
        {
            return View();
        }
    }
}

Capstone/FarmStore3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FarmStore3.Models;

namespace FarmStore3.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Farm()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Capstone/FarmStore3/Views/Farm/AddProduce.cshtml
@model FarmStore3.Models.AddProductViewModel

@{
    ViewData["Title"] = "AddProduce";
}

<h1>AddProduce</h1>

<h4>AddProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProduce">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProduceName" class="control-label"></label>
                <input asp-for="ProduceName" class="form-control" />
                <span asp-validation-for="ProduceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProduceID" class="control-label"></label>
                <input asp-for="ProduceID" class="form-control" />
                <span asp-validation-for="ProduceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockQuantity" class="control-label"></label>
                <input asp-for="StockQuantity" class="form-control" />
                <span asp-validation-for="StockQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InSeason" /> @Html.DisplayNameFor(model => model.InSeason)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Capstone/FarmStore3/Views/Farm/Cart.cshtml
@{
    ViewData["Title"] = "Cart";
}

<h1>Cart</h1>

Capstone/FarmStore3/Views/Farm/CartView.cshtml
@{
    ViewData["Title"] = "CartView";
}

<h1>CartView</h1>

Capstone/FarmStore3/Views/Farm/FarmStore.cshtml
@{
    ViewData["Title"] = "FarmStore";
}

<h1>FarmStore</h1>

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="Products">Product List</a>
</li>

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="GetProduct">Product Search</a>
</li>

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="UpdateProduce">Update Produce</a>
</li>

Capstone/FarmStore3/Views/Farm/FarmStoreView.cshtml
@{
    ViewData["Title"] = "FarmStoreView";
}

<h1>Welcome to our Farm!</h1>

Capstone/FarmStore3/Views/Farm/GetProduct.cshtml
@{
    ViewData["Title"] = "GetProduct";
}

<h1>Get Product</h1>

<h4>search for the product by name.</h4>

<form asp-controller="Farm" asp-action="GetAllProduce">
    <label>First Name of Product</label>
    <input type="text" name="productName" />
    <button>Get</button>
</form>

Capstone/FarmStore3/Views/Farm/Home.cshtml
@{
    ViewData["Title"] = "Home";
}

<h1>Home</h1>

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="GetAllProduce">Products List</a>
</li>

Capstone/FarmStore3/Views/Farm/Produce.cshtml
@model FarmStore3.Models.ProductViewModel

@{
    ViewData["Title"] = "Customers";
}

<h1>List of Produce</h1>

<div>
    <ul>
        @foreach (var product in Model.ListOfProducts)
        {
            <li>
                <a asp-controller="Farm" asp-action="GetAllProduce" asp-route-id="@product.Name">@product.ID</a>
            </li>
        }
    </ul>
</div>


<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Capstone/FarmStore3/Views/Farm/Product.cshtml
@model FarmStore3.Models.Products

@{
    ViewData["Title"] = "Product";
}

<h1>Product</h1>

<div>
    <h4>Products</h4>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.ProduceName)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.ProduceName)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.ProduceID)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.ProduceID)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.StockQuantity)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.StockQuantity)
    </dd>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Capstone/FarmStore3/Views/Farm/UpdateProduce.cshtml
@model FarmStore3.DAL.Models.FarmDALModel

@{
    ViewData["Title"] = "UpdateProduce";
}

<h1>UpdateProduce</h1>

<h4>FarmDALModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateProduce" asp-route-id="@Model.ProduceID">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProduceID" class="control-label"></label>
                <input asp-for="ProduceID" class="form-control" />
                <span asp-validation-for="ProduceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProduceName" class="control-label"></label>
                <input asp-for="ProduceName" class="form-control" />
                <span asp-validation-for="ProduceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockQuantity" class="control-label"></label>
                <input asp-for="StockQuantity" class="form-control" />
                <span asp-validation-for="StockQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CartQuantity" class="control-label"></label>
                <input asp-for="CartQuantity" class="form-control" />
                <span asp-validation-for="CartQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InSeason" /> @Html.DisplayNameFor(model => model.InSeason)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Capstone/FarmStore3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Capstone/FarmStore3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FarmStore3</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FarmStore3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="FarmStore">Farm Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="Cart">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Farm" asp-action="Home">List of Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - FarmStore3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>